resolver: lts-13.10
flags: {}

packages:
  - profunctor-arrows
  - profunctor-optics
  - profunctor-optics-th
extra-deps:
  - github: cmk/property
    commit: 8c6527acfc44af301190a3bbbc7c36b33a9b4fc1
  - github: cmk/connections
    commit: 51aa231014643f6eb93ba0c7a72bdc31b4fd46a1
  - github: cmk/rings
    commit: 5115fea78e9c9a2fff1ed75915d6d5d60f730606
