resolver: lts-13.10
flags: {}

packages:
  - profunctor-arrows
  - profunctor-optics
extra-deps:
  - github: cmk/property
    commit: 8c6527acfc44af301190a3bbbc7c36b33a9b4fc1
  - github: cmk/connections
    commit: 7968f3163548f4935f7faeb6d8e980dd5006719e
  - github: cmk/rings
    commit: 42ad29f7b42ed9f02fb4e78510d22aed7ad78dcd
