resolver: lts-13.10
flags: {}

packages:
  - profunctor-arrows
  - profunctor-optics
  - profunctor-optics-th
extra-deps:
  - github: cmk/property
    commit: 8c6527acfc44af301190a3bbbc7c36b33a9b4fc1
  - github: cmk/connections
    commit: a45bdf0483cc7f8e06b21a7d872ccb04877ffc38
  - github: cmk/rings
    commit: 838243cae84c3b025e1f363360b2f4f746b79f66
