version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup --skip profunctor-optics:doctest
      - run:
          name: Run tests
          command: stack --no-terminal test --skip profunctor-optics:doctest
